#' @include utilities.R surv_summary.R
NULL
#'Plot Survival Tables
#'
#'@description Plot survival tables:
#'\itemize{
#' \item \code{ggrisktable()}: Plot the number at risk table.
#' \item \code{ggcumevents()}: Plot the cumulative number of events table.
#' \item \code{ggcumcensor()}: Plot the cumulative number of censored subjects, the number of subjects who
#'  exit the risk set, without an event, at time t. Normally, users don't need
#'  to use this function directly.
#' \item \code{ggsurvtable()}: Generic function to plot any survival tables.
#'}
#'Normally, users don't need to use this function directly. Internally used by the function
#'  \code{\link{ggsurvplot}}.
#'
#'
#'@inheritParams ggsurvplot_arguments
#'@param fit an object of class survfit. Can be a list containing two
#'  components: 1) time: time variable used in survfit; 2) table: survival table
#'  as generated by the internal function .get_timepoints_survsummary(). Can be
#'  also a simple data frame.
#'@param survtable a character string specifying the type of survival table to plot.
#'@param risk.table.type risk table type. Allowed values include: "absolute" or
#'  "percentage": to show the \bold{absolute number} and the \bold{percentage}
#'  of subjects at risk by time, respectively. Use "abs_pct" to show both
#'  absolute number and percentage. Used only when survtable = "risk.table".
#'@param title the title of the plot.
#'@param xlog logical value. If TRUE, x axis is tansformed into log scale.
#'@param y.text logical. Default is TRUE. If FALSE, the table y axis tick
#'  labels will be hidden.
#'@param y.text.col logical. Default value is FALSE. If TRUE, the table tick
#'  labels will be colored by strata.
#'@param fontsize text font size.
#'@param font.family character vector specifying text element font family, e.g.: font.family = "Courier New".
#'@param hjust horizontal justification of the table text (passed to
#'  \code{geom_text}). Default is 0.5 (centered); use e.g. 0 for left-aligned.
#'@param obscure.less.than optional integer for small-cell suppression
#'  (disclosure control). When set, any table count below this value is replaced
#'  by the label \code{"<n"} (e.g. \code{obscure.less.than = 5} shows \code{"<5"}
#'  for at-risk / event / censor counts of 1--4), so small, potentially
#'  patient-identifying counts are hidden. For the combined risk-table types
#'  (\code{"nrisk_cumevents"}, \code{"nrisk_cumcensor"}) each count in the cell is
#'  masked independently. Applies to the risk table and the cumulative
#'  event/censor tables; it does not affect the \code{ncensor.plot} bar chart.
#'  Default \code{NULL} applies no masking (output unchanged). Requested in
#'  survminer issue #637.
#'@param obscure.zero logical. When \code{obscure.less.than} is set, should a
#'  count of 0 also be masked? Default \code{FALSE} keeps zeros visible (only
#'  positive counts below the threshold are hidden).
#'@param ... other arguments passed to the function \code{\link{ggsurvtable}} and \code{\link[ggpubr]{ggpar}}.
#'@return a ggplot.
#'@author Alboukadel Kassambara, \email{alboukadel.kassambara@@gmail.com}
#' @examples
#' # Fit survival curves
#' #:::::::::::::::::::::::::::::::::::::::::::::::
#'require("survival")
#'fit<- survfit(Surv(time, status) ~ sex, data = lung)
#'
#'# Survival tables
#' #:::::::::::::::::::::::::::::::::::::::::::::::
#' tables <- ggsurvtable(fit, data = lung, color = "strata",
#'   y.text = FALSE)
#'
#' # Risk table
#' tables$risk.table
#'
#' # Number of cumulative events
#' tables$cumevents
#'
#' # Number of cumulative censoring
#' tables$cumcensor

#' @describeIn ggsurvtable Plot the number at risk table.
#' @export
ggrisktable <- function (fit, data = NULL,
                         risk.table.type = c("absolute", "percentage", "abs_pct", "nrisk_cumcensor", "nrisk_cumevents"),
                         ...)
{
  ggsurvtable(fit, data, survtable = "risk.table", ...)
}

#' @describeIn ggsurvtable Plot the cumulative number of events table
#' @export
ggcumevents <- function (fit, data = NULL, ...)
{
  ggsurvtable(fit, data, survtable = "cumevents", ...)
}

#' @describeIn ggsurvtable Plot the cumulative number of censor table
#' @export
ggcumcensor <- function (fit, data = NULL, ...)
{
  ggsurvtable(fit, data, survtable = "cumcensor", ...)
}

#' @describeIn ggsurvtable Generic function to plot survival tables: risk.table, cumevents and cumcensor
#' @export
ggsurvtable <- function (fit, data = NULL, survtable = c("cumevents",  "cumcensor", "risk.table"),
                         risk.table.type = c("absolute", "percentage", "abs_pct", "nrisk_cumcensor", "nrisk_cumevents"),
                         title = NULL, risk.table.title = NULL, cumevents.title = title, cumcensor.title = title,
                         color = "black", palette = NULL, break.time.by = NULL,  xlim = NULL,
                         xscale = 1, xlab = "Time", ylab = "Strata",
                         xlog = FALSE, legend = "top",
                         legend.title = "Strata", legend.labs = NULL,
                         y.text = TRUE, y.text.col = TRUE,
                         fontsize = 4.5, font.family = "", hjust = 0.5,
                         axes.offset = TRUE,
                         ggtheme = theme_survminer(),
                         tables.theme = ggtheme,
                         obscure.less.than = NULL, obscure.zero = FALSE, ...)
{

  if(is.data.frame(fit)){}
  else if(.is_list(fit)){
    if(!all(c("time", "table") %in% names(fit)))
      stop("fit should contain the following component: time and table")
  }
  else if(!.is_survfit(fit))
    stop("Can't handle an object of class ", class(fit))

  # Define time axis breaks
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  xmin <- ifelse(xlog, min(c(1, fit$time)), min(c(0, fit$time), na.rm = TRUE))
  if(is.null(xlim)) xlim <- c(xmin, max(fit$time))
  times <- .get_default_breaks(fit$time, .log = xlog)
  if(!is.null(break.time.by) &!xlog) times <- .time_breaks(break.time.by, max(c(fit$time, xlim)))



  # Surv summary at specific time points
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  if(.is_survfit(fit)){
    data <- .get_data(fit, data = data)
    survsummary <- .get_timepoints_survsummary(fit, data, times)
  }
  else if(.is_list(fit)){
    survsummary <- fit$table
  }
  else if(inherits(fit, "data.frame")){
    survsummary <- fit
  }

  opts <- list(
    survsummary = survsummary, times = times,
    survtable = survtable, risk.table.type = risk.table.type,  color = color, palette = palette,
    xlim = xlim, xscale = xscale,
    title = title, xlab = xlab, ylab = ylab, xlog = xlog,
    legend = legend, legend.title = legend.title, legend.labs = legend.labs,
    y.text = y.text, y.text.col = y.text.col,
    fontsize = fontsize, font.family = font.family, hjust = hjust,
    axes.offset = axes.offset,
    ggtheme = ggtheme, tables.theme = tables.theme,
    obscure.less.than = obscure.less.than, obscure.zero = obscure.zero, ...)

  res <- list()
  time <- strata <- label <- n.event <- cum.n.event <- NULL

  # Ploting the cumulative number of events table
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

  if("cumevents" %in% survtable){
    opts$survtable = "cumevents"
    opts$title <- ifelse(is.null(cumevents.title),
                         "Cumulative number of events", cumevents.title)
    res$cumevents <- do.call(.plot_survtable, opts)

  }

  if("cumcensor" %in% survtable){
    opts$survtable = "cumcensor"
    opts$title <- ifelse(is.null(cumcensor.title),
                         "Cumulative number of events", cumcensor.title)
    res$cumcensor <- do.call(.plot_survtable, opts)

  }
  if("risk.table" %in% survtable){
    opts$survtable = "risk.table"
    if(is.null(risk.table.title)) opts$title <- NULL
    else opts$title <- risk.table.title
    res$risk.table <- do.call(.plot_survtable, opts)
  }


  if(length(res) == 1) res <- res[[1]]
  res
}








# Small-cell suppression for disclosure control (#637, requested by @jwallib):
# when `less.than` is a number, cell counts below it are replaced with the label
# "<less.than" so small, potentially patient-identifying counts are not shown. A
# count of 0 is kept unless `zero = TRUE`. `less.than = NULL` (the default of the
# `obscure.less.than` argument) disables masking entirely, so the tables are
# byte-identical to before. `.obscure_mask()` returns the rows to hide (compared
# NUMERICALLY, so combined string labels like "10 (2)" are masked per component,
# never lexically); `.obscure_label()` overwrites those rows in a label vector.
.obscure_mask <- function(x, less.than, zero) {
  num <- suppressWarnings(as.numeric(as.character(x)))
  !is.na(num) & num < less.than & (num > 0 | zero)
}
.obscure_label <- function(label, mask, less.than) {
  label <- as.character(label)
  label[mask] <- paste0("<", less.than)
  label
}

# Helper function to plot a specific survival table
.plot_survtable <- function (survsummary, times, survtable = c("cumevents", "risk.table", "cumcensor"),
                             risk.table.type = c("absolute", "percentage", "abs_pct", "nrisk_cumcensor", "nrisk_cumevents"),
                         color = "black", palette = NULL, xlim = NULL,
                         xscale = 1,
                         title = NULL, xlab = "Time", ylab = "Strata",
                         xlog = FALSE, legend = "top",
                         legend.title = "Strata", legend.labs = NULL,
                         y.text = TRUE, y.text.col = TRUE, fontsize = 4.5,
                         font.family = "", hjust = 0.5,
                         axes.offset = TRUE, origin.align = TRUE,
                         ggtheme = theme_survminer(), tables.theme = ggtheme,
                         obscure.less.than = NULL, obscure.zero = FALSE,
                          ...)
{

  survtable <- match.arg(survtable)
  risk.table.type <- match.arg(risk.table.type)

  # Normalise the disclosure-control threshold once (#637): require a single
  # value and coerce it to a number so masking is always a NUMERIC comparison
  # (a numeric string like "5" works; a factor is read by its label via
  # as.character(), NOT its integer level code -- the same coercion .obscure_mask
  # uses, so a factor("5") threshold does not silently under-mask). A length != 1
  # or non-numeric value errors rather than mis-masking. NULL leaves masking off.
  if(!is.null(obscure.less.than)){
    if(length(obscure.less.than) != 1L)
      stop("`obscure.less.than` must be a single number, or NULL.", call. = FALSE)
    obscure.less.than <- suppressWarnings(as.numeric(as.character(obscure.less.than)))
    if(is.na(obscure.less.than))
      stop("`obscure.less.than` must be a single number, or NULL.", call. = FALSE)
  }

  # Defining plot title
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  if(is.null(title)){

    if(survtable == "risk.table"){
      risk.table.type <- match.arg(risk.table.type)
      title <- switch(risk.table.type,
                      absolute = "Number at risk",
                      percentage = "Percentage at risk",
                      abs_pct = "Number at risk: n (%)",
                      nrisk_cumcensor = "Number at risk (number censored)",
                      nrisk_cumevents = "Number at risk (number of events)",
                      "Number at risk")

    }
    else
    title <- switch(survtable,
                    cumevents = "Cumulative number of events",
                    cumcensor = "Number of censored subjects"
                    )
  }

  # Legend labels
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  if(is.null(color))
    color <- .strata.var <- "strata"
  else if(color %in% colnames(survsummary))
    .strata.var <- color
  else
    .strata.var <- "strata"

  # Number of strata and strata names
  .strata <- survsummary[, .strata.var]
  strata_names <- .levels(.strata)
  n.strata <- length(strata_names)

  # Check legend labels and title
  if(!is.null(legend.labs)){
    if(n.strata != length(legend.labs))
      warning("The length of legend.labs should be ", n.strata )
    else survsummary$strata <- factor(survsummary$strata, labels = legend.labs)
  }
  else if(is.null(legend.labs))
    legend.labs <- strata_names



  # Adjust table y axis tick labels in case of long strata
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  yticklabs <- rev(levels(survsummary$strata))
  n_strata <- length(levels(survsummary$strata))
  if(!y.text) yticklabs <- rep("\\-", n_strata)
  else if(!.ggplot2_ge_4() && ((is.logical(y.text.col) && isTRUE(y.text.col[1])) || is.character(y.text.col)))
    # On ggplot2 < 4.0 these labels are rendered with ggtext::element_markdown()
    # below (coloured per strata), so HTML-escape <, >, & to render them literally
    # instead of as markdown/HTML tags (#532). No-op for ordinary labels; when
    # y.text.col is FALSE the labels use plain element_text and are left untouched.
    # On ggplot2 >= 4.0 we use element_text() (see below), which shows the label
    # literally, so no escaping is needed (and would show "&gt;").
    yticklabs <- .escape_markdown(yticklabs)

  time <- strata <- label <- n.event <- cum.n.event  <- cum.n.censor<- .cumlabel <- NULL

  # cumevents / cumcensor tables honour risk.table.type: "absolute" (default,
  # the raw cumulative count, unchanged), "percentage" (count as a percent of
  # the stratum size), or "abs_pct" ("count (pct)") (#499). The other risk-table
  # types (nrisk_*) have no cumulative meaning and fall back to the count.
  .cum_pct <- function(count) round(count / survsummary$strata_size * 100)

  # Ploting the cumulative number of events table
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  if(survtable == "cumevents"){
    survsummary$.cumlabel <- switch(risk.table.type,
      percentage = .cum_pct(survsummary$cum.n.event),
      abs_pct    = paste0(survsummary$cum.n.event, " (", .cum_pct(survsummary$cum.n.event), ")"),
      survsummary$cum.n.event)
    # Mask small cumulative-event counts (whole cell, since every variant here is
    # derived from cum.n.event) when disclosure control is requested (#637).
    if(!is.null(obscure.less.than))
      survsummary$.cumlabel <- .obscure_label(survsummary$.cumlabel,
        .obscure_mask(survsummary$cum.n.event, obscure.less.than, obscure.zero),
        obscure.less.than)
    mapping <- aes(x = time, y = rev(strata),
                   label = .cumlabel, shape = rev(strata))
  }
  else if (survtable == "cumcensor"){
    survsummary$.cumlabel <- switch(risk.table.type,
      percentage = .cum_pct(survsummary$cum.n.censor),
      abs_pct    = paste0(survsummary$cum.n.censor, " (", .cum_pct(survsummary$cum.n.censor), ")"),
      survsummary$cum.n.censor)
    # Mask small cumulative-censor counts, keyed on cum.n.censor (#637).
    if(!is.null(obscure.less.than))
      survsummary$.cumlabel <- .obscure_label(survsummary$.cumlabel,
        .obscure_mask(survsummary$cum.n.censor, obscure.less.than, obscure.zero),
        obscure.less.than)
    mapping <- aes(x = time, y = rev(strata),
                   label = .cumlabel, shape = rev(strata))

  }
  else if (survtable == "risk.table"){
    # risk table labels depending on the type argument
    pct.risk <- abs_pct.risk <- n.risk <- NULL
    llabels <- switch(risk.table.type,
                      percentage = survsummary$pct.risk,
                      abs_pct = paste0(survsummary$n.risk, " (", survsummary$pct.risk, ")"),
                      nrisk_cumcensor = paste0(survsummary$n.risk, " (", survsummary$cum.n.censor, ")"),
                      nrisk_cumevents = paste0(survsummary$n.risk, " (", survsummary$cum.n.event, ")"),
                      survsummary$n.risk
    )
    # Small-cell suppression (#637). For the combined "n.risk (count)" types each
    # count is masked independently (so a large n.risk beside a small event count
    # is not over-hidden); for the single-value types (absolute / percentage /
    # abs_pct) the displayed cell derives from n.risk, so the whole cell is masked
    # when the at-risk count is small. Guarded by obscure.less.than != NULL, so the
    # default output is unchanged.
    if(!is.null(obscure.less.than)){
      .mask_n <- function(v) .obscure_label(v, .obscure_mask(v, obscure.less.than, obscure.zero),
                                            obscure.less.than)
      llabels <- switch(risk.table.type,
        nrisk_cumcensor = paste0(.mask_n(survsummary$n.risk), " (",
                                 .mask_n(survsummary$cum.n.censor), ")"),
        nrisk_cumevents = paste0(.mask_n(survsummary$n.risk), " (",
                                 .mask_n(survsummary$cum.n.event), ")"),
        .obscure_label(llabels,
          .obscure_mask(survsummary$n.risk, obscure.less.than, obscure.zero),
          obscure.less.than))
    }
    survsummary$llabels <- llabels
    mapping <- aes(x = time, y = rev(strata),
                   label = llabels, shape = rev(strata))

  }


  # Plotting survival table
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  .expand <- ggplot2::waiver()
  .hjust <- hjust
  # Tables labels offset from origin. With axes.offset = FALSE the table panel
  # starts exactly at x = 0 (like the curve), so the t = 0 numbers-at-risk should
  # sit at x = 0 to line up with the curve's t = 0. Historically they were nudged
  # right to max(xlim)/30, which misaligned them (#645, #302, #448). On a linear
  # axis we now keep them at x = 0 and left-align only the t = 0 column (a centred
  # number at x = 0 would be clipped by the panel edge); interior columns keep the
  # user's hjust. On a log axis x = 0 cannot be shown, so the historical
  # relocation is kept. The inset table (risk.table.pos = "in") passes
  # origin.align = FALSE to keep its own positioning geometry unchanged.
  if(!axes.offset){
    .expand <- c(0,0)
    if(origin.align && !xlog){
      .hjust <- ifelse(survsummary$time == 0, 0, hjust)
    } else {
      offset <- max(xlim)/30
      survsummary <- survsummary %>%
        dplyr::mutate(time = ifelse(time == 0, offset, time))
    }
  }

  p <- ggplot(survsummary, mapping) +
    scale_shape_manual(values = 1:length(levels(survsummary$strata)))+
    ggpubr::geom_exec(geom_text, data = survsummary, size = fontsize, color = color, family = font.family, hjust = .hjust) +
    ggtheme +
    scale_y_discrete(breaks = as.character(levels(survsummary$strata)),labels = yticklabs ) +
    coord_cartesian(xlim = xlim) +
    labs(title = title, x = xlab, y = ylab, color = legend.title, shape = legend.title)

  if (survtable == "risk.table")
    p <- .set_risktable_gpar(p, ...) # For backward compatibility

  p <- ggpubr::ggpar(p, legend = legend, palette = palette,...)

  # Customize axis ticks
  #:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  xticklabels <- .format_xticklabels(labels = times, xscale = xscale)
  if(!xlog) p <- p + ggplot2::scale_x_continuous(breaks = times, labels = xticklabels, expand = .expand)
  else p <- p + ggplot2::scale_x_continuous(breaks = times,
                                            trans = "log10", labels = xticklabels)

  p <- p + tables.theme

  if(!y.text) {
    p <- .set_large_dash_as_ytext(p, size = 50)
  }

  # Color table tick labels by strata. On ggplot2 >= 4.0 use element_text() with a
  # per-label colour vector (native, and mergeable with a user-supplied
  # element_text() -- ggtext's element_markdown() is not, which broke risk-table
  # customization under ggplot2 4.x, #557). On ggplot2 < 4.0, where element_text()
  # does not accept a colour vector, keep element_markdown() (it merges fine there).
  if((is.logical(y.text.col) & y.text.col[1] == TRUE) || is.character(y.text.col)){
    ytext.cols <- if(is.character(y.text.col)) y.text.col
                  else .extract_ggplot_colors(p, grp.levels = legend.labs)
    # When y.text = FALSE the labels are an element_markdown() large dash (set
    # above), so the colour must also be element_markdown() to merge; otherwise use
    # element_text() on ggplot2 >= 4.0 for user-override compatibility (#557).
    p <- .set_ytext_colour(p, rev(ytext.cols), markdown = !.ggplot2_ge_4() || !y.text)
  }

  p

}



# For backward compatibility
# Specific graphical params to risk.table
.set_risktable_gpar <- function(p,  ...){
  extra.params <- list(...)
  ggpubr:::.labs(p,
                 font.main = extra.params$font.risk.table.title,
                 font.x = extra.params$font.risk.table.x,
                 font.y = extra.params$font.risk.table.y,
                 submain = extra.params$risk.table.subtitle,
                 caption = extra.params$risk.table.caption,
                 font.submain = extra.params$font.risk.table.subtitle,
                 font.caption = extra.params$font.risk.table.caption)
}


